---
title: "data"
author: "Tess"
date: "10/27/2019"
output: flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(ggridges)
library(readxl)
library(patchwork)
library(viridis)
library(plotly)
library(flexdashboard)
```

The code below imports the instacart online grocery shopping dataset from 2017.

```{r}
library(p8105.datasets)
data("instacart")


instacart_bev =
  instacart %>%
  filter(department == "beverages")
```

create a flexdashboard using plotly

```{r scatter graph}
#plot of diet pepsi vs normal pepsi by day of the week

instacart_bev %>%
  filter(product_name == "Pepsi" | product_name == "Diet Pepsi" | product_name == "Diet Pepsi Wild Cherry" | product_name == "Diet Pepsi Slim Cans" | product_name == "Diet Pepsi Soda" | product_name == "Diet Pepsi Pack") %>%
  mutate(diet = if_else(product_name == "Pepsi", "Pepsi", "Diet Pepsi")) %>%
  group_by(diet, order_hour_of_day) %>%
  summarise(n = n()) %>%
  plot_ly(x = ~order_hour_of_day, y = ~n, color = ~diet, 
          type = "scatter")


```

```{r bar graph}
#beverage purchase per day

instacart_bev %>%
  group_by(order_hour_of_day) %>%
  summarise(n = n()) %>%
  plot_ly(x = ~order_hour_of_day, y = ~n,
          type = "bar") 

```


```{r line graph}
#beverage purchase per day

instacart_bev %>%
  group_by(aisle, order_hour_of_day) %>%
  summarise(n = n()) %>%
  filter(aisle == "tea" | aisle == "coffee") %>%
  plot_ly(x = ~order_hour_of_day, y = ~n,
          color = ~aisle,
          type = "scatter", 
          mode = "line") 

```


